### ISSUE TITLE
Pixiv - Profile links contain redirects

### ISSUE THREAD

**Issue by DisasterInbound** [cilxe/JavaScriptProjects#2]
Hey, thanks for doing this script. 
I used it on Pixiv and it works with the links on artworks but on the View Profile window on the Profile page the links contain redirects.

For example: [https://www.pixiv.net/en/users/24517](https://www.pixiv.net/en/users/24517)

If you review the Home, Twitter and Pawoo buttons each one has a direct link to the address but clicking on View Profile will make them include a redirect. Also, addresses in the bio section of the text also contain redirects.

**Comment by cilxe** [comment]
Sorry for the late reply, about your concerns, I suggest you are using [**Clean-Tracking-URLs**](https://greasyfork.org/en/scripts/456881), try to add the other script of mine [**Direct Link**](https://greasyfork.org/en/scripts/463408), this should take off your concerns.
