### ISSUE TITLE
bilibili使用脚本后很多gui會變得異常卡頓

### ISSUE THREAD

**Issue by Malus-risus** [cilxe/JavaScriptProjects#3]

**Comment by Vinfall** [comment]
粗看了一下代码，默认会添加人工的延迟，所以大概是 #预期行为

https://github.com/cilxe/JavaScriptProjects/blob/16e38f67b7f7ab7701b752bb61f7d1c2c1daf05d/Clean-URLs.js#L998-L1006

大概是 DELAY_TIME 的锅，没仔细看脚本不确定是拿来干嘛的

https://github.com/cilxe/JavaScriptProjects/blob/16e38f67b7f7ab7701b752bb61f7d1c2c1daf05d/Clean-URLs.js#L60

**Comment by Vinfall** [comment]
可以尝试修改 DELAY_TIME 的值，比如减去一个零康康效果？

```js
const DELAY_TIME = { fast: 60, normal: 100, slow: 300 }; 
```

**Comment by Malus-risus** [comment]
> 可以尝试修改 DELAY_TIME 的值，比如减去一个零康康效果？
> 
> ```js
> const DELAY_TIME = { fast: 60, normal: 100, slow: 300 }; 
> ```

事实证明没有任何作用

**Comment by Vinfall** [comment]
那我就爱莫能助了🤷🏼，仔细看代码分析吧。
