### ISSUE TITLE
[bug] [Clean-Tracking-URLs] B站视频播放页加载变久、缓冲变得极慢。右侧推荐视频不显示封面。

### ISSUE THREAD

**Issue by razilong** [cilxe/JavaScriptProjects#6]
示例：https://www.bilibili.com/video/BV1h4421X7rD
![image](https://github.com/cilxe/JavaScriptProjects/assets/97635957/ebc7c75e-2fea-4d9c-8d9a-547d042672de)

约25%概率出现：点开一个视频到开始播放的这段时间，变长。
较高概率出现：点击进度条，缓冲时间变得很长。当视频时长越长，缓冲越久得明显。
小概率出现：评论区完全不显示或者长时间显示“评论区正在加载中” ，偶尔会出现右侧推荐视频不显示封面以及UP主头像和充电、关注按钮

**Comment by cilxe** [comment]
后续会逐步进行优化。
