### ISSUE TITLE
【BUG】1688搜索时会把后缀转换成其他编码

### ISSUE THREAD

**Issue by itshardforname** [cilxe/JavaScriptProjects#7]
如图片所示，搜索的文字由于是直接加在url后面，在净化的时候会转到其他编码格式，1688前端再转就变成了锟斤拷
![image](https://github.com/cilxe/JavaScriptProjects/assets/51430375/8e19dfc9-b914-4e02-af43-3f8bcaec6e03)

**Comment by cilxe** [comment]
感谢反馈，这边暂时未复现，待后续观察。

**Comment by itshardforname** [comment]
1688更新了前端，已经不会出现乱码。
