### ISSUE TITLE
[建议][Clean-URLs] 列出已添加的自定义参数

### ISSUE THREAD

**Issue by JerryYang-30** [cilxe/JavaScriptProjects#8]
忘记在某些网站添加了哪些自定义参数，想移除都不知道填啥了😂希望可以列出该网站添加了哪些自定义参数

**Comment by JerryYang-30** [comment]
> ##
好吧，我自己实现这个功能了😂而且在移除自定义参数的同时也会显示已添加的。（我没学过js，用AI帮忙写的，写的烂轻喷）

## 效果如图：
![grdmz3rd o0c](https://github.com/user-attachments/assets/6e233713-625b-499f-a980-6e4bfad30c5b)
![m2ocyvy0 crw](https://github.com/user-attachments/assets/adaf42a4-95ff-43c5-8d05-02acb9a4e5ca)
![mooa21b5 ekk](https://github.com/user-attachments/assets/e11e46b7-f40a-4424-9bd8-a6091c9cc7fc)

## 如果懒得改代码，直接`Ctrl A` + `Ctrl C`这个文本就行：
[Clean-URLs-Modified.json](https://github.com/user-attachments/files/16903229/Clean-URLs-Modified.json)

## 代码改动如下（只改了从v0.7.7原代码1354行开始的Main Function）：

### 函数：添加了get和show自定义参数的function（未做 简/繁/英 转换，用的都是简体中文提示）：

```
// (插入原1385行到1386行之间)
// get all custom added param
function getCustomParams(storedArray) {
    let list; // eslint-disable-next-line no-undef
    if (GM_getValue(pageHost)) { // eslint-disable-next-line no-undef
        list = GM_getValue(pageHost);
    } else {
        list = [];
    } // eslint-disable-next-line no-undef
    return list;
}
// show all custom added param
function showCustomParams() {
    let list = getCustomParams(siteParams);
    if (list.length > 0) {
        alert('已添加的自定义参数: ' + list.join(', '));
    } else {
        alert('尚未添加任何自定义参数！');
    }
}

```
### 脚本菜单：添加查看自定义参数的菜单，修改了remove自定义参数的菜单（保留了原来的function removeCustomAddedParam(inputParam)，并调用它）：

```
// (插入原1494行到1495行之间)
GM_registerMenuCommand('查看已添加的自定义参数', showCustomParams);
// eslint-disable-next-line no-undef
GM_registerMenuCommand(MenuRemoveParam, () => { // Menu: Remove custom added param
    let list = getCustomParams(siteParams);
    if (list.length > 0) {
        let inputParam = prompt('已添加的自定义参数: ' + list.join(', ') + '\n\n' + MenuRemoveParam, '');
        removeCustomAddedParam(inputParam);
    } else {
       alert('尚未添加任何自定义参数！');
    }
});
```

**Comment by cilxe** [comment]
Thanks for your contribution, some functions will be added to the script at the next version.

**Comment by JerryYang-30** [comment]
> Thanks for your contribution, some functions will be added to the script at the next version.

😁Don't forget to sync updates on [Greasy Fork](https://greasyfork.org/zh-CN/scripts/456881-%E8%B7%9F%E8%B8%AA%E9%93%BE%E6%8E%A5%E5%87%80%E5%8C%96)
